// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleManagement.Data;

namespace VehicleManagement.Data.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    partial class VehicleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("VehicleManagement.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newId()");

                    b.Property<int>("BodyType")
                        .HasColumnName("BodyType")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(40);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnName("Brand")
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int>("Doors")
                        .HasColumnName("Doors")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Make")
                        .HasColumnName("Make")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("Model")
                        .HasColumnType("TEXT")
                        .HasMaxLength(40);

                    b.Property<decimal>("Price")
                        .HasColumnName("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
